const STUDENT_LIST = 'STUDENT_LIST'
const PROGRAM_LIST = 'PROGRAM_LIST'
const CLASS_LIST = 'CLASS_LIST'
const COURSE_LIST = 'COURSE_LIST'
const CAMPUS_LIST = 'CAMPUS_LIST'
const PRESENCE_LIST = 'PRESENCE_LIST'
const SET_PROGRAM_ID = 'SET_PROGRAM_ID'
const SET_COURSE_ID = 'SET_COURSE_ID'
const SET_TITULO = 'SET_TITULO'
const SET_CLASS_ID = 'SET_CLASS_ID'
const SET_CAMPUS_ID = 'SET_CAMPUS_ID'
const SET_EVASION = 'SET_EVASION'

export {
  STUDENT_LIST,
  PROGRAM_LIST,
  COURSE_LIST,
  CLASS_LIST,
  CAMPUS_LIST,
  PRESENCE_LIST,
  SET_COURSE_ID,
  SET_PROGRAM_ID,
  SET_CLASS_ID,
  SET_TITULO,
  SET_CAMPUS_ID,
  SET_EVASION
}
